# Generated by Django 5.1.6 on 2025-02-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('course_number', models.IntegerField()),
                ('instructor_name', models.CharField(max_length=255)),
                ('duration', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'University Classes',
            },
        ),
    ]
